### ISSUE TITLE
Missing IOTMs causing logic errors

### ISSUE THREAD

**Issue by Imrah25** [Kasekopf/loop-casual#42]
1) [ I do not have camel which would otherwise be used here] Desert exploration will slot compass into the offhand and put kramco on lefty to burn delay. However this causes the creation of sausages to fail as it is expecting to find the grinder equipped but cannot access it to make a sausage. 

2) EDIT: Defiled nook is not even attempted without camel, there is a `ready: () => get("camelSpit") >= 100,` that prevents it from running.

**Comment by Kasekopf** [comment]
Thanks for the reports! These should be fixed now, although you may have to increase the limit on Defiled Nook without a camel to spit.

**Comment by Imrah25** [comment]
I had tried that fix for kramco, unfortunately mafia still cant find it half the time. Should i just try to disable sausage diet for desert locally?
